spring.application.name=Cat
# conexão com o servidor do DB
spring.datasource.url=jdbc:mysql://localhost:3306/catmanager_db

# Usuario do banco
spring.datasource.username=root

# Senha para o acesso do meu usuário
spring.datasource.password=root

# Atualizar a nossa tabela(matriz) automaticamente
spring.jpa.hibernate.ddl-auto=update


thecatapi.key=live_LvPKYLeztuWc4wiXl1HEdDCiwtxd1TD3QxduXk4zX2RYU010KCgEYi45KB4Ian5P